import openai
import pandas as pd
import time

df3 = pd.read_csv(r"C:\Users\Patrick\PycharmProjects\Scrapping\contact_list_2.csv")

# Empty list that'll be used as a bin for the messages generated by ChatGPT
messages = []

# Loop that connects to ChatGPT via the API
# Gives it a name from the file brought in the above pd.read_csv statement
# Makes ChatGPT write a message and appends it to the
for i in range(len(df3['Name'])):
    # This print statement is just to track where the program is in the loop
    print(df3['Name'].values[i])
    API_KEY = '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'
    openai.api_key = API_KEY
    # Makes ChatGPT generate a personalized message
    name = df3['Name'].values[i]
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "user", "content": f"Write a Power BI consulting sales pitch to in 125 words or less to a Finance   \
             leader named {name}. End the message with 'Thanks, the DataTouches team' \
             Make a new line before you say thanks. Don't include a subject line or phone number. \
             Do not use conjunctions in the email"}
        ]
    )
    # This is the output from the JSON that ChatGPT gives you
    chatgpt_response = response['choices'][0]['message']['content']
    chatgpt_response_edited = chatgpt_response.strip("\n").strip()

    # Puts the message generated by ChatGPT into the messages list
    messages.append(chatgpt_response_edited)
    time.sleep(45)

# Creates a DataFrame from the messages variable, then exports a .csv file
df_messages = pd.DataFrame(messages)
df_messages.to_csv('ChatGPT_messages_2.csv')
